name: InSpec Tests

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install dependencies
      run: gem install inspec

    - name: Run tests
      run: inspec exec tests